databases:
  - name: blogist
    databaseName: blogist_production
    user: blogist

services:
  - type: web
    name: blogist
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blogist
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false